<a href="https://colab.research.google.com/github/rajkonkret/PythonAnalizaDanych28-07-2025A/blob/master/zad1_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Początek programu **Pogrubiony tekst** \
 <br>
nowa linia
# Nowa sekcja
## Nowa sekcja


In [1]:
print("witaj w notatniku...")

witaj w notatniku...


In [2]:
a=5
b=6

In [3]:
a, b

(5, 6)

In [4]:
print(a, b)

5 6


In [ ]:
c=9

Celowo nie uruchamiam wiersza c=9 by wygenerować błąd

In [5]:
print(c)

NameError: name 'c' is not defined

# Biblioteka Numpy
Napisana w C do szybkich operacji na danych tablicowych
Podstawowy element: ndarray

In [6]:
!pip install numpy
# !pip install numpy==2.2.0

In [7]:
import numpy as np

In [8]:
lista = [2, 3, 4, 6, 8, 10]
lista

[2, 3, 4, 6, 8, 10]

In [9]:
a = np.array(lista)
a

array([ 2,  3,  4,  6,  8, 10])

In [10]:
print(a)

[ 2  3  4  6  8 10]


In [12]:
print(a.dtype)

int64


In [13]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(a.shape)

(6,)


In [16]:
p = np.zeros((3,3))
p

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
print(p.dtype)

float64


In [19]:
q = np.ones((2,2))
print(q)
q.dtype

[[1. 1.]
 [1. 1.]]


dtype('float64')

In [21]:
r = np.full((2,2), 4.)
print(r)
print(r.dtype)

[[4. 4.]
 [4. 4.]]
float64


In [22]:
r = np.full((2,2), 4)
print(r)
print(r.dtype)

[[4 4]
 [4 4]]
int64


In [23]:
s = np.eye(4)
print(s)
print(s.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


In [24]:
t = np.random.random((3,3))
print(t)
print(t.dtype)

[[0.51647585 0.54053196 0.30428362]
 [0.05629795 0.03438452 0.82724417]
 [0.0748482  0.86887027 0.30770933]]
float64


In [25]:
lista2 = [[5,6], [7,8]]
b = np.array(lista2)
print(lista2)
print(b)

[[5, 6], [7, 8]]
[[5 6]
 [7 8]]


ravel() - spłaszczenie

In [26]:
print(b.ravel())

[5 6 7 8]


In [27]:
print(b[0])

[5 6]


In [28]:
print(b[0,0])
print(b[0,1])

5
6


In [30]:
print(np.float64(21))

21.0


In [31]:
print(np.int64(22.0))

22


In [32]:
print(np.float64(0.1) + np.float64(0.2))

0.30000000000000004


In [33]:
print(np.float32(0.1) + np.float32(0.2))

0.3


In [34]:
print(np.bool(21))

True


In [35]:
print(np.float64(True))

1.0


In [36]:
arr = np.arange(1, 11, dtype=np.float64)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
print(arr.dtype)

float64


reshape() - zmiana kształtu

In [38]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
new_arr = arr.reshape(4,3)
new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
arr2 = np.arange(13)
new_arr2 = arr2.reshape(4,3)
new_arr2

ValueError: cannot reshape array of size 13 into shape (4,3)

In [42]:
new_arr  = arr.reshape(3,4)
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
new_arr = arr.reshape(3,3)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,3)

In [52]:
new_arr = arr.reshape(3, -1) # -1 - dopasuje wymiar automatycznie
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
new_arr = arr.reshape(-1,2,2)
new_arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

ravel() - zwraca widok, operacja na nowym widoku "tablicy" wpływają na zmiany oryginalnej tablicy

In [48]:
print(new_arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


flatten() - spłaszcza, ale robi kopię\
zmiany nie wpływają na oryginalną tablicę

In [49]:
print(new_arr.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [54]:
flat = new_arr.flatten()
rav = new_arr.ravel()

In [55]:
flat[0] = 999
rav[1] = 888

In [56]:
new_arr

array([[  0, 888,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

transpose() - zamienia osie

In [57]:
print(new_arr.transpose())

[[  0   4   8]
 [888   5   9]
 [  2   6  10]
 [  3   7  11]]


resize() - zmienia rozmiar tablicy\
zmienia oryginalna tablice (inplace)\
brakujące elementy wypełnia zerami

In [58]:
new_arr.resize(1,12)
print(new_arr)

[[  0 888   2   3   4   5   6   7   8   9  10  11]]


In [59]:
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
print(np.__version__)

2.0.2


broadcasting - wykonanie operacji na wszystkich elementach tablicy

In [61]:
lista1 = [1,2,3]
print(2 * lista1)

[1, 2, 3, 1, 2, 3]


In [62]:
arr2 = 2 * arr1 # kazdy element listy zostanie przemnożony
arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [63]:
arrx = arr1 + arr2
arrx

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

hstack() - skleja horyzontalnie

In [64]:
arr3 = np.hstack((arr1, arr2))
print(arr3)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


vstack() - skleja pionowo

In [66]:
arr4 = np.vstack((arr1, arr2))
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


concatenate() - łączy we wskazenej osi

In [67]:
arr5 = np.concatenate((arr1, arr2), axis=0)
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [68]:
arr6 = np.concatenate((arr1, arr2), axis=1)
arr6

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [69]:
arre1 = np.array([1,2,3])
print(arre1)
arre2 = np.array([4,5,6])
print(arre2)

[1 2 3]
[4 5 6]


In [71]:
np.concatenate((arre1, arre2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [72]:
np.concatenate((arre1, arre2), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [73]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


dstack() - łączy jako kolumny

In [75]:
arr7 = np.dstack((arr1, arr2))
arr7

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

In [77]:
arr8 = np.arange(4,7)
print(arr8)
ar9 = 2 * arr8
ar9

[4 5 6]


array([ 8, 10, 12])

In [78]:
arr_col_stack = np.column_stack((arr8, ar9))
print(arr_col_stack)

[[ 4  8]
 [ 5 10]
 [ 6 12]]


In [79]:
arr_row_stack = np.row_stack((arr8, ar9))
print(arr_row_stack)

[[ 4  5  6]
 [ 8 10 12]]


/tmp/ipython-input-79-2319927613.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  arr_row_stack = np.row_stack((arr8, ar9))


In [80]:
arr10 = np.arange(1,10).reshape(3,3)
print(arr10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
arr_spli = np.hsplit(arr10, 3)
print(arr_spli)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [82]:
arr_v_split = np.vsplit(arr10, 3)
print(arr_v_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [84]:
arr11 = np.arange(1, 10).reshape(3,3)
print("Tablica w typie integer:", arr11.dtype)

Tablica w typie integer: int64


In [85]:
arr12 = arr11.astype(float)
print("Zmieniony typ na:", arr12.dtype)

Zmieniony typ na: float64


In [86]:
list1 = arr11.tolist()
print(list1)
print(type(list1))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [87]:
arr13 = np.arange(1,5).reshape(2,2)
arr13

array([[1, 2],
       [3, 4]])

In [88]:
arr_copy = arr13.copy()
arr_view = arr13.view()
arr_no_copy = arr13

In [89]:
print("Pierwotna tablica", id(arr13))
print("Kopia głeboka", id(arr_copy))
print("Kopia płytka", id(arr_view))
print("Referencja:", id(arr_no_copy))

Pierwotna tablica 137103599318864
Kopia głeboka 137103605410928
Kopia płytka 137103599317328
Referencja: 137103599318864


In [91]:
arr13[1] = [99, 100]

In [92]:
print("widok:", arr_view)

widok: [[  1   2]
 [ 99 100]]


In [93]:
print("Kopia:", arr_copy)

Kopia: [[1 2]
 [3 4]]


In [94]:
arr14 = np.arange(0, 10)
print(arr14)
print(arr14[3:6])
print(arr14[2:7:2]) # co drugi

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[2 4 6]


In [95]:
arr15 = np.arange(21, 41, 2)
print(arr15)

[21 23 25 27 29 31 33 35 37 39]


In [97]:
print(arr15[arr15 > 30 ])

[31 33 35 37 39]


In [98]:
arr16 = np.arange(1,21).reshape(5,4)
print(arr16)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [99]:
print(arr16[1:3, [1,2]])
slicer = [1,2]
# arr[col, row]

[[ 6  7]
 [10 11]]


In [100]:
arr17 = np.arange(1,5).reshape(2, 2)
arr18 = np.arange(5,9).reshape(2, 2)
print(arr17 + arr18)

[[ 6  8]
 [10 12]]


wczytanie csv

In [102]:
input_stock_price_array = np.genfromtxt(
    '/content/AAPL_stock_price_example.csv',
    delimiter=",", names=True, usecols=(1))

In [103]:
print(input_stock_price_array.size)

229


In [104]:
print(input_stock_price_array[:5])

[(157.919998,) (142.190002,) (148.259995,) (147.929993,) (150.75    ,)]


In [106]:
sorted_stock_price = np.sort(input_stock_price_array)[::-1]
print(sorted_stock_price[0])

(267.100006,)


In [107]:
temp_array = []
with open('/content/AAPL_stock_price_example.csv', "r") as input_file:
    all_lines = input_file.readlines()
    for each_line in all_lines:
        for value_from_line in each_line.rsplit(',')[1:]:
            clean_value = value_from_line.replace("\n", "")
            temp_array.append(clean_value)

In [108]:
print(temp_array[:5])

['Close', '157.919998', '142.190002', '148.259995', '147.929993']


In [109]:
print(len(temp_array))

230
